### ISSUE TITLE
Could you please provide the original data

### ISSUE THREAD

**Issue by wuyeyanjiuyuan** [shivaditya-meduri/transvalorResearchProject#1]
Hello shivaditya-meduri：

I would like to try to run your program, but there is no data set. Whether it is convenient for you to provide the original data set, no matter what the result is, thank you very much. My email is 570774013@qq.com

**Comment by shivaditya-meduri** [comment]
Hello,
I appreciate your interest in this code. I used this code with Transvalor company's private dataset. Unfortunately, The company did not permit me to open source the dataset. I would suggest you check out other data sources which might be of interest to you (https://paperswithcode.com/dataset/simjeb) or you can also try reaching out to Transvalor requesting access to this dataset (https://www.transvalor.com/en/contact). Have a nice day!
